=== daninemcsik/Szakdolgozat/Alkalmazás/Source_code/bin/XML/Content.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Content" xmlns:tns="http://www.example.org/Content" elementFormDefault="qualified">

	<xs:element name="notelist">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="note" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
						
							<xs:element name="noteName" type="xs:string"/>
							<xs:element name="id" type="xs:int"/>
							<xs:element name="pagelist">
								<xs:complexType>
									<xs:sequence>
									
										<xs:element name="page" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
												
													<xs:element name="pageName" type="xs:string"/>
													<xs:element name="pageText" type="xs:string"/>
													<xs:element name="pageId" type="xs:int"/>
													<xs:element name="noteId" type="xs:int"/>
													
												</xs:sequence>
											</xs:complexType>	
										</xs:element>
										
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>	
	</xs:element>

</xs:schema>

=== daninemcsik/Szakdolgozat/Alkalmazás/Source_code/bin/XML/ContentTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>

<notelist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://www.example.com/Content.xsd">

	<note>
		
		<noteName></noteName>
		<id></id>
		<pagelist>
		
			<page>
				<pageName></pageName>
				<pageText></pageText>
				<pageId></pageId>
				<noteId></noteId>
			</page>
			
		</pagelist>
		
	</note>

</notelist>
